version: 2
jobs:
  build:
    working_directory: /go/src/github.com/mistsys/go-tenable
    environment:
      TEST_RESULTS: /tmp/test-results
    docker:
      - image: circleci/golang:1.10
    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS
      - run:
          # to be replaced with vgo?
          name: "Update all the dependencies"
          command:
            go get -u ./...
      - run:
          name: "junit report"
          command:
            go get github.com/jstemmer/go-junit-report
      - run:
          name: "github-release"
          command:
            go get github.com/mistsys/github-release
      - run:
          name: "run unit tests"
          command: |
            trap "go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
            make test 2>&1 | tee ${TEST_RESULTS}/go-test.out

      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output

      - store_test_results:
          path: /tmp/test-results
